### ISSUE TITLE
Ignorant usage leads to errors

### ISSUE THREAD

**Issue by rreinecke** [gdede-hua/Decision_Survey_Platform#8]
The following cases lead to errors. These should have been tested through automated test and should not lead to a crash of the application.

- [x] Starting a research (why isn't that called survey as well btw.?) without an existing user group.
- [x] Creating a user group without selecting any users.
- [x] Not part of the review but still a suggestion: it would be good if you can end a survey process before the set date has passed. Currently it is not possible to make any modifications as soon as it is running.

**Comment by rreinecke** [comment]
Also it is possible to set end dates in the past and add surveys with empty names.
This doesn't seem well tested to me.
Still this doesn't lead to being able to verify the results. How can I test your algorithm without having to wait now?

**Comment by fabian-s** [comment]
@gede-hua to me these seem like valid criticisms re. the functionality and stability of the software you'd like JOSS to publish and the quality of automated testing in your code. Please engage with these issues. 

please also note that these reviews become a lot simpler for us reviewers/editors if your commit messages explicitly reference the respective issues they are meant to fix, or if your messages in these issue threads explicitly reference the commits that were intended to fix them.

**Comment by gdede-hua** [comment]
Dears,
Thank you for your comments. 
Please be kindly informed that additional html validations are now included in order address the raised issues by @rreinecke. You may find the commit here: https://github.com/gdede-hua/Decision_Survey_Platform/commit/cc829099be6181fb744b327bb042dcc64abdb164.

Moreover, a complete survey button has been added in order to get the results and not waiting the end of date.
Finally, "Research" has been replaced by "survey".

**Comment by fabian-s** [comment]
@rreinecke are you satisfied with these changes? if so, please close this issue. 
if not, please make a note what is still missing here.
